### ISSUE TITLE
Gegevenstype Datumtijd heeft geen formaat

### ISSUE THREAD

**Issue by Zevenberge** [edustandaard/doorstroomtoets#16]
Het gegevenstype `Datumtijd` heeft geen gespecificeerd formaat. Het [normatieve document](https://www.edustandaard.nl/app/uploads/2023/05/Doorstroomtoets-Specs-v1.0-definitief-20230512.pdf) verwijst door naar de `doorstroom-openapi.yaml`. Hierin staat

```yml
      datumtijd:
          title: Datumtijd
          type: string
          description: Datum en tijdstip van aanmaken van de Deelnemerslijst.
          format: date-time
          example: 2023-04-06T17:00:00Z
```

Er staat als voorbeeld van een datumtijd `2023-04-06T17:00:00Z`. Dit doet mij persoonlijk aan de gangbare [ISO-standaard](https://en.wikipedia.org/wiki/ISO_8601) denken. Vanochtend hebben wij met externe partijen uitgewisseld en onze ISO-string werd niet geaccepteerd. Los van wie er "gelijk" heeft, betekent dit dat er een verschil van interpretatie is over hoe het koppelvlak eruit hoort te zien. Dit lijkt me niet een discussie die beslecht wordt door wie de stevigste honkbalknuppel in de schuur heeft staan. Het zou welkom zijn als Edustandaard daar een conventie voor kan vastleggen. Zijn millisecondes bijvoorbeeld optioneel of verboden? Moet de tijd altijd in UTC geleverd worden (`Z`) of mag het ook lokale tijd zijn (`+02:00`)?

Ter referentie, bij bijvoorbeeld de geboortedatum staan zowel in de `.yaml` als in het normatieve document een specificatie:

```yaml
geboortedatum:
          title: Geboortedatum
          type: string
          description: "Geboortedatum van de onderwijsdeelnemer. Dit gegeven is noodzakelijk voor vermelding op het leerlingrapport. Waarde is datum volgens formaat EEYY-MM-DD van ISO 8601, bijvoorbeeld 2010-12-31."
          format: date
```

Een korte beschrijving als deze zou al enorm helpen om ons wat meer te sturen.
